spring.application.name=discovery-service
server.port=8761
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:disoverydb

# Enable Azure AI Search profile for vector embeddings
spring.profiles.active=azure-ai-search