spring.application.name=restaurant-service
server.port=8081
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:restauranttestdb
spring.datasource.driver-class-name=org.h2.Driver

# JPA configs
# Hibernate automatically manage the database schema based on the defined JPA entities.
spring.jpa.hibernate.ddl-auto=update

# Show SQL for debugging 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Initialize database automatically every excecution 
# spring.jpa.defer-datasource-initialization=true